# SPDX-FileCopyrightText: Nextcloud GmbH
# SPDX-FileCopyrightText: 2025 Iva Horn
# SPDX-License-Identifier: GPL-3.0-or-later

name: Documentation

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target SwiftNextcloudUI \
            --output-path ./docs \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path /swiftnextcloudui
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs